version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_papper
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/nginx/certs/
      - ./build:/etc/nginx/www