version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_papper
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/nginx/certs/
      #- ./error.log:/var/log/nginx/error.log
      #- ./access.log:/var/log/nginx/access.log